### ISSUE TITLE
Add support for .compact?

### ISSUE THREAD

**Issue by joelthelion** [tom-james-watson/old-reddit-redirect#1]
I've wanted a similar extension for mobile for a very long time, that would redirect to .compact (https://reddit.com/.compact for example).

I think this could be a nice addition to your extension. What do you think? If you think this is a good idea I could even try to submit a PR.

**Comment by tom-james-watson** [comment]
Honestly it's probably better to exist as its own extension - I'd rather this extension just does the one redirect. Don't want to need to add options pages.

Feel free to fork and submit your own extension. It should be pretty easy.

**Comment by joelthelion** [comment]
Thanks, that's precisely why I wanted to check with you first.

**Comment by joelthelion** [comment]
So I went ahead and made my own: https://github.com/joelthelion/compact-reddit-redirect
Took me about 15 minutes thanks to your great work!

**Comment by tom-james-watson** [comment]
Cool! Nice job.

It'd be better if you used a different icon, just to avoid confusion. Maybe even just changing the hue of the image or something.

**Comment by joelthelion** [comment]
Done! Changed the hue to match the compact color theme (more or less).

**Comment by tom-james-watson** [comment]
Perfect. I've actually started using it now myself :thumpsup:
