### ISSUE TITLE
https://old.reddit.com/r/funny/ is now using v.redd.it

### ISSUE THREAD

**Issue by thutt** [tom-james-watson/old-reddit-redirect#104]
I have found as of this filing that some subreddits are pointing to v.redd.it, which loads the new design.

For example, clicking on this:

  https://v.redd.it/d847h5xy197c1

resolves to this:

  https://www.reddit.com/r/funny/comments/18m1bmb/i_cant_take_no_more/

The text of the link is this, in old.reddit.com/r/funny, in case you want to search it:

 ([I... can't... take... no... more](https://v.redd.it/d847h5xy197c1) 
 ([v.redd.it](https://old.reddit.com/domain/v.redd.it/))

It would be nice if this could be transformed into an old.reddit.com link, because the new format is awful.

**Comment by MaoShizhong** [comment]
@thutt Just tested this in Chrome 120.0 and Firefox 121.0 and https://v.redd.it/d847h5xy197c1 resolves correctly to https://old.reddit.com/r/funny/comments/18m1bmb/i_cant_take_no_more/
(confirmed it does not redirect to old reddit when the extension is disabled)

**Comment by tom-james-watson** [comment]
Yeah, this seems to work as expected (now?), so closing this out.
