### ISSUE TITLE
Notification about edge case with /s/ shortened reddit links -

### ISSUE THREAD

**Issue by sunlightspectre** [tom-james-watson/old-reddit-redirect#105]
I've noticed that when people use short links -  
Links, from reddit, with an /s/ in the url - 

The result cannot be read on old.reddit, and instead lead to a certification page, or a submit link.  

You recently fixed this - links from _reddit.com_ will now redirect to readable, full-reddit links.  
Wonderful, many thanks!  
But occasionally, users will send links that have old.reddit _and_ the shortened links.  
These will still redirect to a security certificate notification. I don't know if it's possible to add a re-redirect for these -   
One that redirects to new reddit so it can complete the link and redirect to old reddit -  
But just in case anyone else is searching, I wanted to outline the behaviour and why it's happening.

Thank you so much for your endless hard work. It is appreciated beyond measure.

**Comment by CDelongchamp** [comment]
I was linked this meme and it showcases the mentioned issue:
https://www.reddit.com/r/lotrmemes/s/zPDYiy8oCr

**Comment by tom-james-watson** [comment]
That doesn't match the description of the issue - it's not old.reddit.com. It also redirects to https://old.reddit.com/r/lotrmemes/comments/1dkxlki/nasty_stepsisters_are_precious/ for me, so it seems to work fine?

@sunlightspectre do you have an example URL?

**Comment by cyberblade3001** [comment]
I am affected by this; have been for a while. Also on Firefox.

Using the link above (https://www.reddit.com/r/lotrmemes/s/zPDYiy8oCr) and this plugin enabled I am redirected to https://old.reddit.com/r/lotrmemes/submit?url=https%3A%2F%2FzPDYiy8oCr 

When I disable the plugin the link redirects to https://www.reddit.com/r/lotrmemes/comments/1dkxlki/nasty_stepsisters_are_precious/?share_id=WqLo7a691DFwwW-qxrvrd

I checked with disabling RES to see if there was a conflict; but didn't see a difference. Happy to check other things or provide additional info if its helpful.

**Comment by tom-james-watson** [comment]
I have never been able to recreate this. Can you please try disabling ALL other extensions and trying again?
