### ISSUE TITLE
Mod pages incorrectly redirect to old.reddit

### ISSUE THREAD

**Issue by meetc0** [tom-james-watson/old-reddit-redirect#106]
Mod pages using the updated mod pages located in the directory reddit.com/mod do not exist at the subdomain old.reddit.com

**Comment by tom-james-watson** [comment]
Do you have example URLs?

**Comment by meetc0** [comment]
https://www.reddit.com/mod/<subreddit>/automations
https://www.reddit.com/mod/<subreddit>/insights
https://www.reddit.com/mod/<subreddit>/automations

Note: you must be a moderator of a subreddit to be able to view the appropriate page.

**Comment by YousufSSyed** [comment]
@tom-james-watson Have u looked at this?

**Comment by Oneechan69** [comment]
@tom-james-watson Have u looked at this?

**Comment by tom-james-watson** [comment]
No, if I had there would be an update here. PRs are welcome.

**Comment by skippybosco** [comment]
> No, if I had there would be an update here. PRs are welcome.

I have submitted a PR for this issue. Thanks for the consideration.

https://github.com/tom-james-watson/old-reddit-redirect/pull/133

**Comment by tom-james-watson** [comment]
Closed by https://github.com/tom-james-watson/old-reddit-redirect/pull/133.

Thanks @skippybosco! 🫶

This is awaiting review as 1.8.2 on Firefox and 2.0.1 on Chrome and so should be published over the next few days.
