### ISSUE TITLE
Request option to set default comment sort order?

### ISSUE THREAD

**Issue by mosource21** [tom-james-watson/old-reddit-redirect#108]
It would be great if you could set the default comment sort order instead of having to click on the small Sorted By list and selecting every time you view a different post?

Example: on an appropriate depth of Reddit URL add `?sort=new` to the end of the URL being accessed (for example I prefer sorted on new)?

```
?sort=new
?sort=top
?sort=controversial
?sort=old
?sort=qa
```

Thanks

**Comment by tom-james-watson** [comment]
Hello!

I don't really want to bloat the scope of what this extension does, so it's not something I'd want to add, I'm afraid.
