### ISSUE TITLE
Support Firefox for Android by using .compact

### ISSUE THREAD

**Issue by benjaminoakes** [tom-james-watson/old-reddit-redirect#11]
For example, https://www.reddit.com/r/funny vs https://www.reddit.com/r/funny.compact. The compact version is basically the old Reddit for mobile, which loads *significantly* faster.

On Firefox for Android, this should be used instead. The string `.compact` needs to be added at the end of the URL or before the first `?` so it doesn't conflict with the query string.

Thanks for making this extension!

**Comment by tom-james-watson** [comment]
Somebody already forked this repo and made a version that does exactly this. The wonders of open source!

https://github.com/joelthelion/compact-reddit-redirect

**Comment by benjaminoakes** [comment]
Oh, thanks!  I searched before making the issue, but didn't find that.  🤷‍♂️
