### ISSUE TITLE
does not work simultanoeusly with uBlock Origin Lite

### ISSUE THREAD

**Issue by saurik** [tom-james-watson/old-reddit-redirect#110]
I am using Firefox and recently added the uBlock Origin Lite extension. Today, I realized that I was no longer getting automatic old.reddit.com redirection, and managed to track it down to some kind of conflict with this extension. I have not yet tried to figure out what is going on, though wonder if https://github.com/EFForg/https-everywhere/issues/14961 might be relevant and informative (it might be neither).

**Comment by saurik** [comment]
FWIW, this can be worked around by disabling uBlock Origin Lite (as in, setting it to "no filtering") for reddit.com. (I am surprised it took me two weeks to try such.)

**Comment by tom-james-watson** [comment]
Not much we can do about incompatibilities like this, unfortunately. Glad you found a workaround.
