### ISSUE TITLE
Extension disabled after update due to new permissions

### ISSUE THREAD

**Issue by u1735067** [tom-james-watson/old-reddit-redirect#116]
Hi, 

this extension got disabled after an update on Edge, as it requires new permissions:
<img width="337" alt="image" src="https://github.com/tom-james-watson/old-reddit-redirect/assets/1735067/a872bcd0-6834-479f-9f52-4001901c5d42">

Is "Block content on all pages" (the second) an expected permission? Is it possible to limit it's scope?

Thank you for this extension btw!

**Comment by tom-james-watson** [comment]
See https://github.com/tom-james-watson/old-reddit-redirect/issues/117. It's not possible to limit the scope, no.
