### ISSUE TITLE
ℹ️ New permissions due to manifest v3 migration

### ISSUE THREAD

**Issue by tom-james-watson** [tom-james-watson/old-reddit-redirect#117]
The extension on Chrome was recently migrated to manifest v3 - https://github.com/tom-james-watson/old-reddit-redirect/pull/115

This was a mandatory migration that needed to happen for the extension to not be removed from the web store.

With manifest v3, the only way to implement the same functionality is to use the [declarativeNetRequest API](https://developer.chrome.com/docs/extensions/reference/api/declarativeNetRequest), which shows in permissions as "Block content on any page". See https://developer.chrome.com/docs/extensions/reference/permissions-list.

The extension also triggers a request for a new permission for old.reddit.com, which is also due to the way manifest v3 interprets the extension. But that permission is obviously pretty understandable.

**Comment by wjandrea** [comment]
Just in case anyone else is wondering why the permission says "Block content on any page":

> The `chrome.declarativeNetRequest` API is used to block or modify network requests by specifying declarative rules. This lets extensions modify network requests without intercepting them and viewing their content, thus providing more privacy.

-- [chrome.declarativeNetRequest](https://developer.chrome.com/docs/extensions/reference/api/declarativeNetRequest)

**Comment by Kobold** [comment]
I my few extensions like a hawk and the updated permission request concerned the heck out of me. Thank you for the transparency and all the hard work on this extension @tom-james-watson, and the permission details @wjandrea.

**Comment by Kyu** [comment]
Same here, had to double check haha
