### ISSUE TITLE
Whitelist or method to temporarily disable add-on?

### ISSUE THREAD

**Issue by GwynplaineLLC** [tom-james-watson/old-reddit-redirect#12]
Hey, thanks a lot for making this and I hope you're enjoying the holiday season!

I just wanted to ask if there's a way to temporarily disable the add-on without removing it (e.g. right-click on the button in the Chrome menu to temporarily disable it), or to whitelist the redesign only on certain subreddits?

I ask because I rarely need to check if a redesigned layout has updated appropriately, though I personally prefer to use the old design. Some smaller subreddits have also only continued to update the sidebar/etc. on their redesigned layout, while others have only updated their old design layout unfortunately. Having an easy way to default to the old design but temporarily disable it or the integration of a whitelist/blacklist would be fantastic.

I hate to request features without personally knowing how to implement them (I have no experience with JavaScript, so I'm a bit of a mooch here), but this would be a great QoL addition if possible. Thanks for your consideration!

**Comment by tom-james-watson** [comment]
Instead of adding complexity to the addon, I think a better way would to be to just workaround the issue. You could disable the extension in incognito mode (that's the default anyway) and open the subreddit there, or open a different browser.

**Comment by atbanpc** [comment]
Adding a browser action that can enable and disable the extension would be relatively simple and not add much complexity. I'll make a pull request with it. 

One issue though is that the disabled status will not be retained after the browser is closed without the storage permission. I don't think that will be too much of an issue though.

**Comment by tom-james-watson** [comment]
The extension can now be "disabled" by using the `new.reddit.com` subdomain. So if you want to a given page in new reddit, just change the domain from `old.reddit.com `to `new.reddit.com`.
