### ISSUE TITLE
Can you please make a firefox addon for "new.reddit.com"?

### ISSUE THREAD

**Issue by Bogdanov89** [tom-james-watson/old-reddit-redirect#124]
I apologize for misusing the Issues section here.
Reddit is forcing some new-new UI onto random users and its an impractical buggy mess, especially for desktop users.

There is a firefox addon called "Old New Reddit Redirect" that redirects to the previous "new" reddit UI but it stopped working reliably, now it often gives endless "problem loading page" screens or fails to make reddit load the new.reddit.com version.

Could you please make a new addon that redirects all reddit stuff to "new.reddit.com"?
Thank you!

**Comment by tom-james-watson** [comment]
This add-on was made specifically to avoid "new" reddit, so I have zero interest in making and maintaining an extension for it.

The code is open source and anyone is free to make it if they are motivated enough to.
