### ISSUE TITLE
now needs a dev account to work? possible fix

### ISSUE THREAD

**Issue by bilditup1** [tom-james-watson/old-reddit-redirect#128]
Recently clicked on a link on Google that got rewritten to the old subdomain via your extension in FF 128.0, and got this message: 

![Screenshot 2024-07-16 at 18-20-59 Blocked](https://github.com/user-attachments/assets/cdf37de8-685e-4532-a652-fa593c916dd5)

Seems like a recent change on their part.
FWIW, turning off old reddit redirect allows the page to load on click from the Google link. Turning off the extension, and then manually copying the link, removing the Google crud, and subbing in "old" gets old to load without issue. Leaving in the Google and reddit tracking stuff while changing the subdomain to 'old' results in a visit to an intermediary loading page: 

![Screenshot 2024-07-16 at 18-38-44 Redirect Notice](https://github.com/user-attachments/assets/352b972f-b483-4656-93b8-30545eb2d0ea)

after which the block appears. The URL looks like this in that case:

https://www.google.com/url?sa=t&source=web&rct=j&opi=XXXXXXXX&url=https://old.reddit.com/r/subreddit/comments/`comment_id`/`comment_title`/&ved=random_string_1&usg=random_string_2

Trying to manually copy-paste in a 'clean' old.reddit.com link without everything after the comment title or even comment id does not remove the block within that tab, but it's fine in a new tab. 

The 'easy' conclusion is that removal of the tracking crud before and after the URL would bypass what seems to be a simple rule on their part to the effect of "we do not list 'old' on Google nor do we generate 'ved' or 'usg' on shared links, so if a request to 'old' comes from Google or has those vars set, flag it". I guess from the fact that the same tab stays blocked after this, a temporary cookie is being set?

From looking at `/manifest_v2/background.js` it appears that everything before the hostname is just ignored in construction of the new URL anyway. But `pathname `is either tested for against `excludedPaths`, in which case the URL doesn't get rewritten at all, or passed without being touched. My guess is if we take `pathname` and strip everything after `comment_id` (the title is unnecessary to get to where you need to go, and `comment_id` seems like it's an easy-to-check for pattern), a URL would be constructed that avoids this stupid API flag and need to let them know what extension we're using, which seems to me to be extremely user-hostile and frankly ridiculous. (I'm not sure how to modify or test extensions, and have run out of time today to look into that, or I would try this myself, apologies.)

ED: I haven't checked Chrome/the V3 version, so don't know if the same thing happens there.

**Comment by tom-james-watson** [comment]
Hello!

Can you provide clear reproduction steps?

That warning is what I see if I try and access old reddit while using a VPN and not logged in. It's the only time I've ever seen it. You sure it's not related to that?

**Comment by bilditup1** [comment]
1. Google something
2. Click on link to reddit in the results
3. !profit

VPN is not on, the IP shown was my actual IP, which is why I blotted it out from the screenshot. Firefox Multi-Account Containers is on--this was in a 'personal' tab. Tampermonkey is on but there's nothing there related to Google. uBlock Origin was on but turning it off just now did not affect anything. There are several other extensions but none of them should affect the URL. I can try to do a clean install...somewhere...and see what happens, but probably not tonight or at least not right this minute

**Comment by skippybosco** [comment]
I cannot reproduce the issue following your directions. 

[Screen recording 2024-07-17 2.06.36 PM.webm](https://github.com/user-attachments/assets/df208ca7-bbd4-4ad0-a754-e8a51ae327c4)

**Comment by tom-james-watson** [comment]
Me neither. I think it's more likely that Reddit is blocking your unauthenticated traffic based one whatever heuristics they're using, and it's somehow pushed over the edge by the requests that come from the Google results.

**Comment by bilditup1** [comment]
I am trying to narrow this down. The same client at a different physical location (the same ISP, but a slightly different DNS setup, for what it's worth) has the same problem. Other clients at both locations appear to be OK. I have many extensions, and thought that they were set up the same way on each device, but confirming this could take a while. If this client is sending strange traffic to Reddit or anywhere else, it is not apparent in Wireshark. 
I am not sure what makes traffic 'authenticated' or not, presumably you don't mean 'encrypted'. Whether or not I'm logged in to Reddit doesn't seem to matter, either :(

**Comment by tom-james-watson** [comment]
By authenticated I mean that if I try and load Reddit when using nordvpn, I get that message unless I log in.

**Comment by bilditup1** [comment]
...ok, it seems like there was some strange thing going on with my login cookie within the Personal container. Upon logging out and logging back in within such a tab, I can no longer trigger the warning. (I thought that I had tried this before, but it seems like I was outside that container at the time--not totally clear.) Moreover, links from Google are no longer prefixed in the above fashion when right-click-copying. All very strange and opaque and thus frustrating. I guess if this changes or if I can get it to happen again, I'll update this, but for now this seems like an extreme edge case that might not be worth trying to account for

**Comment by tom-james-watson** [comment]
Ok cool. Yeah I don't think this really is to do with the extension, so will close out 👍
