### ISSUE TITLE
Handle new reddit links properly

### ISSUE THREAD

**Issue by vinayverghese** [tom-james-watson/old-reddit-redirect#131]
Not sure how to describe this exactly, but there is a type of link that does not open if there is a forced redirect to `old.reddit.com`

Example: https://www.reddit.com/r/leetcode/s/9axwW0UHHS

The above link does not work when the extension is enabled.

**Comment by tom-james-watson** [comment]
Works fine for me. Please try with all other extensions disabled.

**Comment by CodeAbuser** [comment]
With this extension installed, the example link above redirects me to a page to submit a new post

https://old.reddit.com/r/leetcode/submit?url=https%3A%2F%2F9axwW0UHHS

**Comment by skippybosco** [comment]
No issue with the example link redirecting to a submit page for me. 

https://github.com/user-attachments/assets/3495eabf-98d3-4f82-93f8-73330e071d96

**Comment by tom-james-watson** [comment]
Works absolutely fine for me both on Firefox (manifest v2) and Chrome (manifest v3).

If you are seeing issues, can you please disable ALL other extensions and try again.

**Comment by vinayverghese** [comment]
@tom-james-watson You're right. I didn't have any reddit related extensions enabled, I just removed some of them altogether and it seems fine now. Not sure which one was the offending one though. I'll go ahead and close the issue now.
