### ISSUE TITLE
New reddit links are redirecting to reddit submit page

### ISSUE THREAD

**Issue by CodeAbuser** [tom-james-watson/old-reddit-redirect#132]
The other issue on this was closed so I'll make my own.

1) using Edge browser
2) no extensions other than this one installed.
3) clicking on this link redirects me to the reddit submit page.  

Example: https://www.reddit.com/r/leetcode/s/9axwW0UHHS

video attached.

https://github.com/user-attachments/assets/96d58c7c-ca11-4778-8a2e-a3ee82d8f1d2

**Comment by tom-james-watson** [comment]
Hello!

Edge is not a supported browser - only Firefox and Chrome are supported.

Can you recreate the issue in either of those?

**Comment by CodeAbuser** [comment]
Edge is the only browser I have. Thanks for confirming. I guess you can
close this issue.
