### ISSUE TITLE
Extension not working either on FIrefox or Chrome. 

### ISSUE THREAD

**Issue by MasterLive013** [tom-james-watson/old-reddit-redirect#135]
Hi, first, thank you for creating and maintaining this extension. But right now the extension is not working either on Firefox or Chrome.

**Comment by skippybosco** [comment]
@MasterLive013 

Can you elaborate on your steps to reproduce as it is working in both FireFox and Chrome on version 2.0.1.

1. What version of Chrome are you using?

2. What version of the extension are you using? (have you verified it is enabled?) 

3. What other extensions do you have enabled? Disable everything but old-reddit-redirect and restart browser. Are you still having issues?

4) What is the exact URL you are testing with? example:

https://www.reddit.com/r/Showerthoughts/comments/1f3j43m/most_superheroes_couldnt_eat_fast_enough_to/

....and what happens when you click the link?

**Comment by MasterLive013** [comment]
1) Version 128.0.6613.114 

2) 2.0.1; it is enabled.

3) I disabled everything but old-reddit-redirect and restarted the browser. I'm still having issues. 

4) It sends me to this page:

https://old.reddit.com/r/Showerthoughts/comments/1f3j43m/most_superheroes_couldnt_eat_fast_enough_to/

![Capture](https://github.com/user-attachments/assets/81384eea-aa8e-4c54-a652-97cf4ca9b29d)

**Comment by tom-james-watson** [comment]
Hi, @MasterLive013 

Sending you to https://old.reddit.com/r/Showerthoughts/comments/1f3j43m/most_superheroes_couldnt_eat_fast_enough_to/ is exactly what it should do. It redirected you from new Reddit (www.reddit.com) to Old Reddit (old.reddit.com).

What was the behaviour you were expecting to see?

**Comment by skippybosco** [comment]
> 4. It sends me to this page:

This is the correct place. I think the confusion is that you have enabled to allow subreddits to show you custom themes, which still display even when using the old site. You can disable that in preference:

https://old.reddit.com/prefs

![image](https://github.com/user-attachments/assets/992fa009-9ad2-413a-a043-5efe60030e4c)

Uncheck "allow subreddits to show me custom themes", push save and then click again here:

https://www.reddit.com/r/Showerthoughts/comments/1f3j43m/most_superheroes_couldnt_eat_fast_enough_to/

It should look like this now:

![image](https://github.com/user-attachments/assets/ae3ddb6a-59a3-44ac-81b5-d7a0e0e6c7cb)

**Comment by MasterLive013** [comment]
Ok, then I guess I'm confused. There is the reddit I can access now (new reddit) which I don't want, there is this old.reddit site I can access when all my other extensions are off (the one I posted the screenshot). 


And then there is this 3rd reddit version of the site which I could access like 24 hours ago which for some reason I'm not able to access anymore.

**Comment by skippybosco** [comment]
This is default reddit with new design: (it assumes preference is set to "Use new Reddit as my default experience" in reddit preference I linked above)

![image](https://github.com/user-attachments/assets/a193382b-da89-4b19-8a81-bcd51424544c)

This is reddit with old design using subreddit theme: (you can disable subreddit themes using the instructions I gave above)

![image](https://github.com/user-attachments/assets/62500eb8-fd45-49ad-bc64-8e3f6a6b0618)

This is reddit with old design with subreddit theme disabled

![image](https://github.com/user-attachments/assets/eef532f7-f1b0-43f7-8eee-ff20bbaf604a)

There is not a lot of complexity with this plugin, it just redirects you to old.reddit.com by default. You can verify the difference yourself by manually going to:

new:

https://new.reddit.com/r/Showerthoughts/comments/1f3j43m/most_superheroes_couldnt_eat_fast_enough_to/

old:

https://old.reddit.com/r/Showerthoughts/comments/1f3j43m/most_superheroes_couldnt_eat_fast_enough_to/

**Comment by tom-james-watson** [comment]
I'd note that Reddit is in the middle of a transition from what was New Reddit to what is effectively a New New Reddit. Old Reddit is effectively now two redesigns old.

Maybe what you were confused by was the change between New and New New. They may still be doing A/B testing with this, meaning sometimes you get one or the other.

Either way, it's nothing to do with this extension, which should always take you to Old Reddit, and that appears to be working for you. Will close this issue out as it's working as expected.
