### ISSUE TITLE
This forefox addon stopped working many days ago

### ISSUE THREAD

**Issue by geedogz** [tom-james-watson/old-reddit-redirect#138]
This addon stopped working. I'm on windows, firefox. My CSS doesnt work on this addon anymore. Please fix

**Comment by tom-james-watson** [comment]
What do you mean your CSS doesn't work? This extension doesn't do anything to do with CSS.

**Comment by skippybosco** [comment]
> This addon stopped working. I'm on windows, firefox. My CSS doesnt work on this addon anymore. Please fix

Take a look at this previous issue:

https://github.com/tom-james-watson/old-reddit-redirect/issues/135

Try the steps included in the replies.

Once all other extensions are disabled except old-reddit-redirect, if you are still seeing issues, post a screenshot here of what you are seeing.
