### ISSUE TITLE
*.reddit.com redirecting to old.reddit.com instead of old.reddit.com/r/*

### ISSUE THREAD

**Issue by mmvahora** [tom-james-watson/old-reddit-redirect#140]
Started happening today. For example, when going to 

https://funny.reddit.com/ 

I get redirected to https://old.reddit.com/ instead of https://old.reddit.com/r/funny/

Has made the website borderline unusable with the extension as clicking on any hyper link to a subreddit redirects you back to https://old.reddit.com/.

**Comment by tom-james-watson** [comment]
Where are you hitting this? Can you paste reproduction steps for where these links can be seen?

**Comment by mmvahora** [comment]
Hmm...actually I think the issue might be related to reddit itself not the extension. On both my desktop (chrome + edge) and iOS (safari), I'm seeing that anytime I try to go to a subreddit using *.reddit.com, they automatically redirect to the homepage https://www.reddit.com/?rdt=<some num> (which the extension redirects to old.reddit.com). 

Don't think this would be intended as many of the subreddits use hyperlinks to other subs in that *.reddit.com format.  Hope it's a bug and it gets resolved. If it's intended than that's gonna be a nuisance for all the mods to fix/update.

**Comment by mmvahora** [comment]
Oh man, they did remove support...what a headache. Many subs/mods won't bother updating, and this will make experience worse :( 

https://old.reddit.com/r/help/comments/1fojw02/cleaning_up_some_lowusage_features/

**Comment by tom-james-watson** [comment]
Alright thanks for looking into it. Honestly though, I don't really ever see links like that.

**Comment by skippybosco** [comment]
They announced it a week ago they were discontinuing subreddit vanity subdomains:

https://old.reddit.com/r/help/comments/1fojw02/cleaning_up_some_lowusage_features/

**Comment by livejamie** [comment]
@mmvahora You can use the Firefox/Chromium extension "Redirector" to fix this.

https://chromewebstore.google.com/detail/redirector/ocgpenflpmgnfapjedencafcfakcekcd?hl=en
https://addons.mozilla.org/en-US/firefox/addon/redirector/

Settings:
```
Example url: https://*.reddit.com/

Include pattern: https://*.reddit.com/

Redirect to: https://old.reddit.com/r/$1

Pattern Type: Wildcard
```

**Comment by livejamie** [comment]
cc @HereticBG @BlakeRunkle1

**Comment by naanlizard** [comment]
Any hope that this extension gets subreddit subdomain redirects as well? I imagine the overlap is large, and I'd prefer one extension over multiple (especially if the others are going to stop working with manifest v3)

**Comment by tom-james-watson** [comment]
IMO that's out of scope for the extension - I don't want to add extra features like this - I want it to just be as simple as possible.

**Comment by naanlizard** [comment]
Fair, thank you for the extension either way of course
