### ISSUE TITLE
Reddit blocks page requests from users with this addon active

### ISSUE THREAD

**Issue by MaximusFullius** [tom-james-watson/old-reddit-redirect#144]
I'm using this addon on the latest version of Firefox. Very recently (as in just the past few days), I've been getting this odd request-blocked message page from Reddit whenever I try to visit it. 

![image](https://github.com/user-attachments/assets/fd73ac2b-3405-4e3d-95f2-15b7719da534)

The text of the message says, 

"whoa there, pardner!

Your request has been blocked due to a network policy.

Try logging in or creating an account [here](https://www.reddit.com/login/) to get back to browsing.

If you're running a script or application, please register or sign in with your developer credentials [here](https://www.reddit.com/wiki/api/). Additionally make sure your User-Agent is not empty and is something unique and descriptive and try again. if you're supplying an alternate User-Agent string, try changing back to default as that can sometimes result in a block.

You can read Reddit's Terms of Service [here](https://www.reddit.com/wiki/api/).

if you think that we've incorrectly blocked you or you would like to discuss easier ways to get the data you want, please file a ticket [here](https://support.reddithelp.com/hc/en-us/requests/new?ticket_form_id=21879292693140).

when contacting us, please include your ip address which is: XXXXXXXXX and reddit account"

Turning off the old-reddit-redirect addon "fixes" this issue.

**Comment by MaximusFullius** [comment]
> When you say it fixes the issue, is it that you are just going to new reddit? If you manually go to old.reddit.com with the extension turned off, do you still see the issue? I suspect that yes. This is the error I see when trying to visit old.reddit.com when not authenticated and running a VPN. If I turn off the VPN then it goes away. So yeh, I suspect this isn't to do with the extension.

Actually today it was different. Reddit still gave me this message after disabling the addon. It wouldn't let me visit the site untiI disabled my VPN. Perhaps this is the reason why I got the message.

**Comment by tom-james-watson** [comment]
Yup, it'll be that
