### ISSUE TITLE
new.reddit redirects to old.reddit in Firefox Private Window(Incognito)

### ISSUE THREAD

**Issue by pubct** [tom-james-watson/old-reddit-redirect#145]
My understanding of the extension behaviour is that, if I visit new.reddit on purpose, it wouldn't redirect. Right? But, in Incognito, it redirects.

I do have RES installed, but I tested with it disabled as well.

Don't know if it's related, I'm logged in in the main window, but not in Incognito.

Thanks.

**Comment by pubct** [comment]
Seems like the only case new.reddit doesn't redirect is if I'm logged in.

If I'm logged out and the cookies cleared, with the extension disabled, accessing new.reddit redirects to www.reddit.

With the extension enabled, accessing new.reddit redirects to old.reddit.

If I'm logged in, new.reddit doesn't redirect no matter disabled or enabled extension.

I guess there's no solution for this then, since it's a server side thing? Shall I close this?

**Comment by skippybosco** [comment]
I can also confirm that with (or without) the extension enabled, from a logged out state Reddit automatically redirects new.reddit.com to reddit.com. 

A consideration for you if you want to avoid old redirect while in incognito is to disable the extension for private browsing:

https://support.mozilla.org/en-US/kb/extensions-private-browsing

This doesn't help fix the reddit server side redirect, but it does help limit what extensions do and don't function in private browsing.

**Comment by tom-james-watson** [comment]
Yeah, I don't think there's anything we can do here, given this is a server side thing, as you say.

**Comment by tom-james-watson** [comment]
And yeh, what @skippybosco suggests would be the workaround here, I guess.

**Comment by pubct** [comment]
Just a comment.
Realized today that new.reddit now redirects to www.reddit when in logged in state.
So, in order to purposely access the new layout in logged in state now, the extension will have to be disabled, while have the "use new Reddit as default" enabled in Reddit preference.

**Comment by tom-james-watson** [comment]
You can use https://sh.reddit.com

**Comment by pubct** [comment]
Didn't know there's that. Thanks.
