### ISSUE TITLE
new.reddit.com doesn't work anymore as bypass URL (but sh.reddit.com works)

### ISSUE THREAD

**Issue by zxcvxzcv-johndoe** [tom-james-watson/old-reddit-redirect#149]
Thanks for this awesome addon!

I have noticed in last few weeks that in Firefox if I go for example https://old.reddit.com/r/hockey/comments/1hf0rse/how_i_set_up_a_netcam_at_nhl_games/ and if I change the URL to https://new.reddit.com/r/hockey/comments/1hf0rse/how_i_set_up_a_netcam_at_nhl_games/ I will get directed back to the https://old.reddit.com/r/hockey/comments/1hf0rse/how_i_set_up_a_netcam_at_nhl_games/ which doesn't show me the photos.

But I can bypass the addon if I go to https://sh.reddit.com/r/hockey/comments/1hf0rse/how_i_set_up_a_netcam_at_nhl_games/ and I will see those pictures in the new version of Reddit.

Any idea why / how the whitelisting of new.reddit.com has broken? 

I actually just now learned about sh.reddit.com so I guess that works for me as a workaround (and its one letter less to type :) )

**Comment by tom-james-watson** [comment]
This is not to do with the extension - reddit itself now redirects new.reddit.com to www.reddit.com - you can confirm yourself if you disable the extension.
