### ISSUE TITLE
Would you consider making best redirect to hot for the front page? That's in the spirit of old Reddit.

### ISSUE THREAD

**Issue by ahartschen** [tom-james-watson/old-reddit-redirect#16]

**Comment by tom-james-watson** [comment]
Hmm - are you saying that this is how reddit used to work? I don't remember this ever being the case, to be honest, though maybe I'm wrong.

I personally wouldn't want hot to be the default, also the only way to do this I think would be to add `/hot/` to the URL when visiting the homepage, which I'm not a fan of. So yeah, I don't think this is something I would want to do.

**Comment by ahartschen** [comment]
Yes, the default "Front Page" used to be **hot**, but now it uses the **best** sorting. Best uses some annoying algorithm that heavily weights subreddits you've visited instead of just showing a collection of all of your subscriptions.

I understand that you may not want to add this because your extensions does one thing and it does it very well. Thank you for it!

**Comment by tom-james-watson** [comment]
Yeah I'd prefer to keep it simple. I'd imagine there would be a tonne of people who would not like the change to be honest. Thanks anyway.
