### ISSUE TITLE
Reddit videos don't redirect to old site

### ISSUE THREAD

**Issue by peskdale** [tom-james-watson/old-reddit-redirect#18]
Video hosted directly on reddit have links using the short url **v.redd.it**. Clicking on any of these videos result in the user being sent to new reddit.

https://old.reddit.com/domain/v.redd.it/

Would be great if the extension could intercept this and rewrite to the old.reddit.com url.

**Comment by tom-james-watson** [comment]
Ah yeah, you're right.

Looks like the following happens:

https://v.redd.it/bme34yys81d31 returns 302 to https://www.reddit.com/video/bme34yys81d31

https://www.reddit.com/video/bme34yys81d31 returns 301 to https://www.reddit.com/r/WTF/comments/ciuxnw/newcastle_in_the_early_mornings/

Are you using Firefox? It seems to happen to me on Skype but not on Chrome. I think this looks like a bug with how Firefox is implementing browser.webRequest.onBeforeRequest

**Comment by peskdale** [comment]
I'm using Chrome, so I'm not sure why we're seeing different behaviour.

**Comment by tom-james-watson** [comment]
Interesting - what platform? Can you try disabling all other extensions and trying again?

**Comment by peskdale** [comment]
Windows 8.1, Chrome 75.0.3770.142

I'm getting inconsistent behaviour - in my regular Chrome session, its sending me to the new site.
Incognito, with all of my other browser extensions still enabled, it's sending me to the old site.

Will investigate further...

**Comment by peskdale** [comment]
Disabling all extensions yields the same result. No redirect on my regular session, redirect incognito.

I'm going to assume this is an annoying caching issue on my Chrome profile, so go with your own observations.
