### ISSUE TITLE
Incorrectly redirects np.* links

### ISSUE THREAD

**Issue by emgreen33** [tom-james-watson/old-reddit-redirect#2]
https://github.com/tom-james-watson/old-reddit-redirect/blob/bc54bb53d90c7efdd7f583afc4c668f8ed031242/background.js#L11

The redirect for `np.reddit.com/*` isn't needed (since np links always load in the legacy design), and breaks the custom styling some subreddits use to enforce No Participation mode

**Comment by tom-james-watson** [comment]
I'm not sure about this. Agreed that it kind of breaks the point of the np. view, but it seems inevitable that they move the np subdomain to render the new domain

**Comment by tom-james-watson** [comment]
I'm going to close this for now given I'm still feeling the same way as my previous comment
