### ISSUE TITLE
Disable redirect for reddit.com/rpan

### ISSUE THREAD

**Issue by IcerOut** [tom-james-watson/old-reddit-redirect#21]
It seems old.reddit.com/rpan doesn't exist, so reddit.com/rpan and reddit.com/rpan/* shouldn't be redirrected

**Comment by tom-james-watson** [comment]
As far as I'm aware this was an experiment that has now ended. I too saw a banner linking to this yesterday, but I think that was because reddit was having issues.

**Comment by tom-james-watson** [comment]
https://www.reddit.com/rpan also loads nothing.

**Comment by IcerOut** [comment]
Ah, in that case my bad. When I saw the banners I thought it was a new feature, not just a temporary test. I guess I'll just close this since it's no longer relevant.

**Comment by tom-james-watson** [comment]
Thanks anyway!

**Comment by h-h-h-h** [comment]
Currently, https://www.reddit.com/rpan plays videos for me!

It seems to come and go. So, an exception should be added, as far as I'm concerned. It can always be removed later.
