### ISSUE TITLE
old.reddit.com no longer displays links to join/subscribe to subreddits.

### ISSUE THREAD

**Issue by Forbo** [tom-james-watson/old-reddit-redirect#25]
I'm thinking this is more of an issue with a dark pattern that Reddit has implemented, rather than an issue with the add-on itself, but I figured this would probably be a good place to raise the question.

The join or subscribe link for subreddits no longer appears in the sidebar on old.reddit.com. Not sure of any way to get it back. As a work around I've been doing the following:

1. Temporarily disable the add-on.
1. Visit the subreddit using www.reddit.com.
1. Click the link to join/subscribe.
1. Re-enable the add-on.

Would it be possible to implement a workaround in the add-on itself to address this issue?

**Comment by tom-james-watson** [comment]
I'm not seeing this issue. The join/leave buttons are there like they always have been and are working as expected.

Are you sure you don't have another extension that is causing this issue? Try disabling all other extensions and trying again?

**Comment by Forbo** [comment]
Looks like the issue was with a rule in uBlock Origin. Took a lot of testing individual add-ons to figure it out. I'll close this now, sorry about that.
