### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by saberworks** [tom-james-watson/old-reddit-redirect#26]
This is related to firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1579734

When installing old-reddit-redirect it asks for permissions to read sites and it lists 3, then it says "Access your data on 2 other sites."  This is a total of 5.  However, when I visit your manifest: https://github.com/tom-james-watson/old-reddit-redirect/blob/master/manifest.json

There are only 4 sites listed.  So it seems like the addon I am installing does not match the source code in this repo.  It's disconcerting because firefox doesn't give me access to the remaining 2 URLs.  For all I know it could be 'gmail.com' or something.

I spent a bit of time looking into this and by following these steps I can view the running background.js script:  about:debugging -> old reddit redirect -> inspect -> debugger -> sources -> background.js

It includes this list of url patterns:

```
    urls: [
      "*://reddit.com/*",
      "*://www.reddit.com/*",
      "*://np.reddit.com/*",
      "*://new.reddit.com/*",
      "*://pay.reddit.com/*"
    ],
```

It seems "pay.reddit.com" is included in the firefox version but not in the current manifest on github.  Does it mean a new firefox version needs to be published or is this expected?

**Comment by tom-james-watson** [comment]
From the extension console: `Last Updated: Dec. 6, 2018`

Basically I've merged a couple of minor PRs that clean up a couple of things but then have never published a new version as they didn't actually change anything. I should probably get round to that though, as you're right ideally the extension should match `master`

**Comment by tom-james-watson** [comment]
Latest version has been released on Firefox: https://addons.mozilla.org/en-US/firefox/addon/old-reddit-redirect/

**Comment by saberworks** [comment]
Awesome, thank you!  Confirmed it installs and lists 4 sites now.  I appreciate it!

**Comment by tom-james-watson** [comment]
No problem.

Have also submitted an update for the chrome extension.
