### ISSUE TITLE
Fix for https://www.reddit.com/rpan

### ISSUE THREAD

**Issue by techboyg5** [tom-james-watson/old-reddit-redirect#29]
https://old.reddit.com/rpan/* doesn't exist. https://www.reddit.com/rpan/* needs to be excluded.

**Comment by tom-james-watson** [comment]
This has been discussed before:

https://github.com/tom-james-watson/old-reddit-redirect/pull/22
https://github.com/tom-james-watson/old-reddit-redirect/issues/21
https://github.com/tom-james-watson/old-reddit-redirect/pull/19

Do you know what the deal is with this thing? It seems to not exist most of the time? Right now it is loading for me.

**Comment by tom-james-watson** [comment]
I'm open to adding an exception but I just don't really understand what that page is / why or when it is available.

**Comment by techboyg5** [comment]
> I'm open to adding an exception but I just don't really understand what that page is / why or when it is available.

RPAN is a livestream service from reddit, similar to Twitch. It is available only sometimes, but here is the reason why:

The [RPAN subreddit](https://old.reddit.com/r/pan/) is accessible from old reddit, but clicking on a broadcast link goes to a 404 page with Old Reddit Redirect installed. This is because RPAN is only available on new reddit, and the links there are forced to open in new reddit for this reason, but ORR redirects it.

As a result, a redditor might think that you can use RPAN on old reddit because the subreddit loads but none of the actual streams work and lead to a 404.

**Comment by tom-james-watson** [comment]
Version 1.2.0 that includes this fix has been submitted to chrome and firefox extension stores. Just waiting for a review.
