### ISSUE TITLE
Should also redirect for amp pages

### ISSUE THREAD

**Issue by catchcase** [tom-james-watson/old-reddit-redirect#30]
e.g.

https://amp.reddit.com/r/GameDeals/comments/gmgvf5/fanatical_tomb_raider_goty_bundle_86_off429/

should redirect to

https://old.reddit.com/r/GameDeals/comments/gmgvf5/fanatical_tomb_raider_goty_bundle_86_off429/

**Comment by h-h-h-h** [comment]
Example of usage in the wild: https://old.reddit.com/r/PublicFreakout/comments/hg4hlf/these_people_can_not_be_serious/fw2cmgv/

**Comment by tom-james-watson** [comment]
Yup - looks like we should definitely add support

**Comment by tom-james-watson** [comment]
This was fixed in v1.2.0 which was released yesterday.
