### ISSUE TITLE
Whitelist privacy settings page

### ISSUE THREAD

**Issue by LivingWithHippos** [tom-james-watson/old-reddit-redirect#32]
Hello, at the moment https://new.reddit.com/settings/privacy does not have an equivalent page https://old.reddit.com/settings/privacy and from what I've seen these options are just not available in the old reddit settings.
Regex for url matching should be 
`details.url.match(/^https?:\/\/(www\.)*reddit.com\/settings\/privacy/)`

**Comment by tom-james-watson** [comment]
Version 1.2.0 that includes this fix has been submitted to chrome and firefox extension stores. Just waiting for a review.
