### ISSUE TITLE
Reddit image galleries are broken

### ISSUE THREAD

**Issue by Lachcim** [tom-james-watson/old-reddit-redirect#33]
As of today, July 15th, 2020, [Reddit natively supports image galleries](https://old.reddit.com/r/announcements/comments/hrrh23/now_you_can_make_posts_with_multiple_images/). These galleries, however, do not work with the `old.reddit.com` subdomain and instead show a "page not found" screen. People in the comments section have already complained of the link being dead for them, presumably because they use Old Reddit Redirect. If Imgur galleries are anything to go by, these new galleries will soon constitute a major part of all image posts.

Are there any plans to add support for this new feature? I would be happy to contribute relevant code, but my previous pull request #5 was struck down as "not lightweight enough".

**Comment by tom-james-watson** [comment]
Oh yeah .. this is going to be pretty widely used soon I imagine.

OK - I think we are going to need to add an exception for these URLs. At that point we may as well throw in the other few pages that people have mentioned, too.

If you're happy to contribute the code, that would be great, as I am pretty busy with other work at the moment :heart:.

You can reopen/recreate https://github.com/tom-james-watson/old-reddit-redirect/pull/5/files and add it to what you had previously suggested for user profiles. Whilst you're at it, may as well also add support for https://github.com/tom-james-watson/old-reddit-redirect/issues/32.

Thanks!

**Comment by tom-james-watson** [comment]
Version 1.2.0 that includes this fix has been submitted to chrome and firefox extension stores. Just waiting for a review.
