### ISSUE TITLE
There's an annoying popup on old.reddit.com for non-subscribers

### ISSUE THREAD

**Issue by fat-tire** [tom-james-watson/old-reddit-redirect#4]
If you're not a Reddit subscriber and are redirected to the old reddit, you get an annoying splash/popup.  There is a "skip for now" link, but when you hit reload, the splash comes right back.

I dunno if this is info is within the scope of what this extension is trying to do, but for informative purposes, in the console you can do something like this to make the splash go away:

```
document.getElementById("onboarding-splash").style.display = "none";
$("body").css("overflow", "visible");
```

**Comment by tom-james-watson** [comment]
I actually haven't seen this popup myself. I'd rather not expland the scope of the extension (for now, at least). You can use [uBlock](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en) to block elements like that.
