### ISSUE TITLE
Intermittent link failure

### ISSUE THREAD

**Issue by Piogre** [tom-james-watson/old-reddit-redirect#41]
Started running into an issue about two weeks ago that I only today was able to track down to this extension as the cause.  During browsing on Firefox (version 80.0.1), intermittently, links to reddit from any source (within reddit, google results, discord, etc) will stop working entirely.  Clicking the link will cause the little icon in the tab header to refresh for a brief moment, but the current page does not change and no further result happens from clicking the link.  Once this happens, it continues to happen until I relaunch Firefox or disable this add-on.

This happens several times a day, to the point where I've now disabled this add-on (causing the issue to now not happen at all).

Unsure what could be causing this, but figured you'd want it brought to your attention.

**Comment by tom-james-watson** [comment]
Never heard of anything like that. The only thing I can think of is that the extensions javascript is erroring somehow,  but I'm not sure how that could happen.

If you download this repository (https://github.com/tom-james-watson/old-reddit-redirect/archive/master.zip), then you should be able to add the extension to your Firefox in development mode and see if there are any errors.

Go to about:debugging#/runtime/this-firefox and press "Load Temporary Addon..." and select the `manifest.json` of the unzipped file. Then press "Inspect" on the loaded extension. From there you should be able to see if there are any errors in the console for the extension when you try and load reddit.

**Comment by Piogre** [comment]
Disregard; disabling the extension made it go away for a couple days then it started happening without the extension too.  Must be an issue with reddit or with firefox.
