### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by dogtopus** [tom-james-watson/old-reddit-redirect#42]
The mobile reddit page is very slow on older phones and has too many distractions. Worse, it has login walls on longer posts. It would be nice to make this work on Firefox Android so the above issue can be resolved.

**Comment by tom-james-watson** [comment]
It actually does work on Firefox Android. It worked perfectly on the old version of Firefox. Unfortunately, on the new version you still can't install any addon you want.

There is a workaround to do it, though - https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly.

**Comment by lazka** [comment]
I've installed this with firefox nightly on Anddroid now, but it doesn't seem to to anything. No redirects etc.

**Comment by tom-james-watson** [comment]
Did you create a custom addon collection?

Can you send screenshots of the addon and details views from setting? Should look like this

![Screenshot_20210822-152732](https://user-images.githubusercontent.com/3852719/130356985-0b3f5f5d-2533-4bd7-9544-5ae5002ea27a.png)
![Screenshot_20210822-152735](https://user-images.githubusercontent.com/3852719/130356987-5886c932-56e1-4b15-b1eb-db6cfb02faa7.png)

**Comment by tom-james-watson** [comment]
It works fine for me, though you have to bear in mind that this is not supported functionality by Firefox yet and so just may be broken on Firefox's end.

**Comment by lazka** [comment]
thanks. It was an error on my end, for some reason it disabled all plugins when I updated the collection and I missed that.

Everything works fine now, thank you!

**Comment by hirorpt** [comment]
I have succeeded in porting old-reddit-redirect to [uBlock Origin's userResourcesLocation](https://github.com/gorhill/uBlock/wiki/Advanced-settings#userresourceslocation). It works fine on fenix stable.
Thank you for the helpful code.

**Comment by droped** [comment]
@hirorpt How did you do it?

**Comment by droped** [comment]
@hirorpt I've downloaded the script if you want to delete yours. Thank you.

**Comment by shodanx2** [comment]
Still seemingly unable to add this addon to firefox for android
Raised an issue with firefox support https://support.mozilla.org/en-US/questions/1415846

**Comment by tom-james-watson** [comment]
You can't add addons via the web interface. The only way to add them is through the app settings, but to add arbitrary addons at the moment you still need to follow these fiddly instructions - https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/.
