### ISSUE TITLE
Desktop vs. mobile use

### ISSUE THREAD

**Issue by gaul** [tom-james-watson/old-reddit-redirect#43]
I read Reddit on both my phone and desktop and send tabs between them to read.  This addon works great when sending to the desktop and I get the intended old experience.  However I prefer the mobile/default experience on my phone.  Perhaps this addon could add a preference on which domain the user desires?  This would require Fenix support discussed in #42 but this could work for existing Beta and Nightly users.

**Comment by tom-james-watson** [comment]
I'm not sure what you mean? If you don' want to be redirected to old.reddit.com on mobile, don't install the extension?

**Comment by gaul** [comment]
I have the extension installed on my desktop which works great.  I send the tabs to my phone via Firefox sync which sends the old.reddit.com/r/foo URL.  I would like to install the addon on my phone as well but redirect all the tabs to reddit.com/r/foo not old.*.

**Comment by tom-james-watson** [comment]
Ah I see. No, I don't think that's something we would support, because that's basically doing the opposite of what this extension does. You could relatively easily make an extension that does do that redirect, though. As you can see from the code, it's very simple.

**Comment by lazka** [comment]
I've installed this with firefox nightly on Anddroid now, but it doesn't seem to to anything. No redirects etc.
