### ISSUE TITLE
Provide `new.reddit.com` exception

### ISSUE THREAD

**Issue by h-h-h-h** [tom-james-watson/old-reddit-redirect#44]
Direct poll and gallery links don't work any more and yield the error message "Internal Server Error".

A possible improvement, going forward, would be not redirecting the explicit `new.reddit.com` anymore, at least with a respective extension setting. So, you can make problematic URLs work when necessary.

Or is automatic post type detection an option? (Not possible by address bar URL.)

See also (poll post link in comments): https://old.reddit.com/r/help/comments/l1ncug/reddit_polls_internal_server_error/

**Comment by tom-james-watson** [comment]
Done! Submitted to Firefox and Chrome stores as 1.3.0. Normally only takes a few hours to be approved.

**Comment by Rtizer-9** [comment]
Related:

Can you please also redirect i.reddit.com and i.i.reddit.com to old.reddit.com. I keep getting them in my google results now and then and then I've to manually click on URL and then edit to get to old reddit.

Thanks.
