### ISSUE TITLE
Provide i.reddit.com and i.i.reddit.com redirection

### ISSUE THREAD

**Issue by Rtizer-9** [tom-james-watson/old-reddit-redirect#45]
Can you please also redirect [i.reddit.com](url) and [i.i.reddit.com](url) to old.reddit.com. I keep getting them in my google results now and then and then I've to manually click on URL and then edit to get to old reddit.

Thanks.

**Comment by h-h-h-h** [comment]
I also encountered Reddit pages with such UIs in Google search results.

**Comment by tom-james-watson** [comment]
Yeah I've actually seen i.reddit.com links on google too. i.i.reddit.com doesn't seem to be a domain though - not sure if you meant something else?

**Comment by tom-james-watson** [comment]
Submitted to extensions stores for review as `1.4.0`.

**Comment by Rtizer-9** [comment]
I'm actually in the habit of using google search operators often in my searches and that's why keep getting such results. I agree that [i.i.reddit.com](url) does not come up as frequent as [i.reddit.com](url) in search results but sometimes I do get this kinda results. For eg:

[https://www.google.com/search?q=cat+site%3Ai.i.reddit.com](url) gives not only `i.i` but `i.i.i.i` results as well. Although it's a `i.i` search so definitely that's what gonna show up but sometimes when you search for a not so common query, it still comes up in the normal `site:reddit.com` results as well. It throws an HSTS error in firefox.

I don't know what's with reddit about these subdomains. There was a thread on reddit where somebody told that there are 26 x 26 subdomains...each with 2 letter combinations for different languages, np for non-participation and so on... for different purposes.

Thanks for the quick update. Really appreciate it.

**Comment by tom-james-watson** [comment]
Well as it doesn't actually load, I think this looks like an error with google - I don't think the extension should need to hotpatch google bugs :smile:

**Comment by Rtizer-9** [comment]
Oh, no I wasn't saying that it loads, I just meant that it comes up in the results and when you click on the result, you've to manually edit the `i.i` part and change it to either `old` or just remove the `i.i` part manually and press enter to get to the desired destination. The last update would suffice except for few exceptional cases so no issues.
