### ISSUE TITLE
Currently not working: Firefox 85.0.2

### ISSUE THREAD

**Issue by njy200** [tom-james-watson/old-reddit-redirect#46]
I think something changed with reddit, but it will no longer try to redirect to old reddit. New reddit is persistent.

**Comment by tom-james-watson** [comment]
I'm currently on Firefox 85.0.1 and it's working fine. I've also just downloaded Firefox Nightly and it's also working fine. Looks like it's likely something on your end. Is the extension definitely enabled? If you're using incognito mode, make sure you set the extension's "Run in private windows" to "Allow".

**Comment by zksmk** [comment]
Are you visiting old bookmarks that use new.reddit.com by any chance? The newest version no longer redirects it, but still redirects www.reddit.com.

**Comment by njy200** [comment]
I am clicking the top results on google as I am fixing some things on my machine. The extension works most of the time but then it’ll just not redirect once in a while.Sent from ProtonMail Mobile On Mon, Feb 22, 2021 at 6:32 AM, zksmk <notifications@github.com> wrote:  
Are you visiting old bookmarks that use new.reddit.com by any chance? The newest version no longer redirects it, but still redirects www.reddit.com.

**Comment by tom-james-watson** [comment]
I can't reproduce that (it's also something I do quite often). Is this on desktop or mobile?

Have you tried disabling all other extensions to see if any of them are interfering in some way?

**Comment by njy200** [comment]
I’m at work at the moment so I’ll have to test it out again. It could be this “smart referrer” extension I added. https://addons.mozilla.org/en-US/firefox/addon/smart-referer/Sent from ProtonMail Mobile On Mon, Feb 22, 2021 at 10:27 AM, Tom Watson <notifications@github.com> wrote:  
I can't reproduce that (it's also something I do quite often). Is this on desktop or mobile?
Have you tried disabling all other extensions to see if any of them are interfering in some way?
