### ISSUE TITLE
Provide exception for draft posts

### ISSUE THREAD

**Issue by Wires77** [tom-james-watson/old-reddit-redirect#48]
Occasionally I'll be linked a draft post in the form of `https://www.reddit.com/user/[user]/draft/[guid]`, which shows a 404 if I try to go there on old Reddit, but shows the draft on new Reddit.  It'd be nice to be able to view those without having to switch to another browser or disable the extension.

**Comment by tom-james-watson** [comment]
Do you have a real example url for me to try? I didn't know drafts were a thing. You can force the new reddit by changing `old` to `new` in the URL, though.

**Comment by Wires77** [comment]
Somehow I missed your reply on this issue until I saw it closed today.  Here is an example draft I just made on my profile: https://www.reddit.com/user/Wires77/draft/6ee064d6-758f-11ec-9997-16fcaccecb26

**Comment by tom-james-watson** [comment]
I get a 404 for that without the extension!

**Comment by Wires77** [comment]
> 

Well, that's because only the author can see their own draft posts...you'd have to make your own in order to see it

**Comment by Wires77** [comment]
> I get a 404 for that without the extension!

Hey @tom-james-watson I just found out that you have to be signed in to access draft links, perhaps that's why you got a 404?  Let me know if the link above works for you, but otherwise you can create your own draft post by creating a post in new Reddit and saving as a draft.
