### ISSUE TITLE
Missing 'applications' in manifest.json prevents local build and install

### ISSUE THREAD

**Issue by C4K3** [tom-james-watson/old-reddit-redirect#49]
Building the zip file locally (simply using `make`) and then trying to install in firefox using "Install Add-On From File" leads to

> This add-on could not be installed because it appears to be corrupt.

with browser console showing

```1622316014992	addons.xpi	WARN	Invalid XPI: Error: Cannot find id for addon /home/C4K3/Downloads/old-reddit-redirect.zip(resource://gre/modules/addons/XPIInstall.jsm:1539:19) JS Stack trace: loadManifest@XPIInstall.jsm:1539:19```

Editing manifest.json to have an `applications.gecko.id` value solves the issue and allows local installation. I'm unsure if there's a reason not to have that in the manifest.json.

**Comment by tom-james-watson** [comment]
That's just a warning - that field does not actually seem to be required. I don't understand what this value is meant to be set to either. I tried some random value and I still cannot install the extension from zip.

What exactly is the motivation here? If you want to run a local version of the app, you can load it as a temporary addon from about:debugging.
