### ISSUE TITLE
Does not redirect to links that explicitly say new.reddit.com

### ISSUE THREAD

**Issue by Evernow** [tom-james-watson/old-reddit-redirect#52]
Hello.

There are communities that for some reason have all their hyperlinks to new.reddit, which the old reddit extension does not overwrite. 

Example: https://new.reddit.com/r/nvidia/comments/nwmjdu/game_ready_driver_46677_faqdiscussion/

**Comment by tom-james-watson** [comment]
What do you mean by their hyperlinks? Because all of the posts go to old.reddit.com as expected for me.

We intentionally allow for loading of the new site by new.reddit.com because people sometimes need to access the new version for various reasons, or because things like the new predictions features don't work.

**Comment by Evernow** [comment]
> What do you mean by their hyperlinks? Because all of the posts go to old.reddit.com as expected for me.

When linked outside of reddit using the new.reddit domain. 

> We intentionally allow for loading of the new site by new.reddit.com because people sometimes need to access the new version for various reasons, or because things like the new predictions features don't work.

Understandable, but not everyone wants this functionality, sometimes someone always wants to be using old reddit regardless of what they are linked to. Could it be possible to have a toggle for this functionality?

**Comment by tom-james-watson** [comment]
I'd prefer to not complicate the extension by adding preferences and things like that.

So you mean people giving you links to new.reddit.com? I don't really know why anyone would ever do that. If you use the new UI you would be on www.reddit.com.

**Comment by Evernow** [comment]
> So you mean people giving you links to new.reddit.com? I don't really know why anyone would ever do that. If you use the new UI you would be on [www.reddit.com](http://www.reddit.com).

I have no idea why people explicitly give the new.reddit.com, but it does happen sadly.

**Comment by tom-james-watson** [comment]
Yeah, it's strange! I think "fixing" this by also redirecting new.reddit.com would be a mistake because it would undo https://github.com/tom-james-watson/old-reddit-redirect/issues/44. I personally use new.reddit.com every now and then, too. I think there's not much we can do here, I'm afraid.

**Comment by konomikitten** [comment]
Is there any chance we could at least get a setting in the add-on to always redirect to `old.reddit.com`, I have a lot of subs that are explicitly linking to `new.reddit.com` and it's getting a bit frustrating to have to change the url constantly.

**Comment by Evernow** [comment]
> 
> 
> Is there any chance we could at least get a setting in the add-on to always redirect to `old.reddit.com`, I have a lot of subs that are explicitly linking to `new.reddit.com` and it's getting a bit frustrating to have to change the url constantly.

I agree. Subreddits are continuously doing this because "Our sub looks best in new".
