### ISSUE TITLE
Not working on some profiles anymore?

### ISSUE THREAD

**Issue by omperus** [tom-james-watson/old-reddit-redirect#6]
Not sure if Reddit changed something or the addon broke, but when i try to view some profiles (not all) the new reddit design shows up even with the domain having the "old." at the start.

I'll leave you this one as an example https://old.reddit.com/user/AlexEquilibrium/

Oh and i forgot to mention, if you are logged in it works as intended (maybe because i have the setting in my account to load the old design), the problem is when you are logged out.

**Comment by Lachcim** [comment]
That's what my pull request #5 attempts to fix. I submitted it three days before this issue was posted, 24 days ago in total. I think it would be beneficial for everyone to finally have it merged.

**Comment by tom-james-watson** [comment]
Cheers for the report.

Yeah, for some reason reddit shows this page regardless of what domain you are on. I don't know if this is an oversight or whether the user pages were migrated to the new design before the redesign proper as a test.

I'm not fixing this as per the comment in https://github.com/tom-james-watson/old-reddit-redirect/pull/5, so I'll close this out.
