### ISSUE TITLE
Make Redirects for Gallery links

### ISSUE THREAD

**Issue by 0lhi** [tom-james-watson/old-reddit-redirect#60]
Here's an example for a Gallery:

https://www.reddit.com/gallery/qnjjvh

Replacing *www* with *old* does not work:

https://old.reddit.com/gallery/qnjjvh

But this does:

https://old.reddit.com/r/OnePiece/comments/qnjjvh

**Comment by tom-james-watson** [comment]
I discovered we can redirect https://www.reddit.com/gallery/qnjjvh to https://old.reddit.com/qnjjvh which will be redirected by reddit to https://old.reddit.com/r/OnePiece/comments/qnjjvh.

This has been submitted to firefox/chrome stores as 1.6.0 with the release notes

> Add an exception for /gallery links to ensure that the full old reddit comments are loaded (https://github.com/tom-james-watson/old-reddit-redirect/issues/60).

Thanks for your contribution.
