### ISSUE TITLE
Login fails with "session expired" with the extension

### ISSUE THREAD

**Issue by matter-it-does** [tom-james-watson/old-reddit-redirect#61]
Steps:

- Clear reddit cookies or use private mode with the extension enabled.
- Click the login button on https://new.reddit.com
- Enter credentials and try to login
- See "Your session has expired. Please refresh the page and try again."

Allowlisting https://www.reddit.com/login from the redirect would solve the issue.

**Comment by tom-james-watson** [comment]
I can't recreate this. I can login fine. Works both from https://old.reddit.com/login and the sidebar.

**Comment by tom-james-watson** [comment]
I've just realised you probably mean you are trying to login at `new.reddit.com`?

**Comment by matter-it-does** [comment]
Yes, just updated the task.

**Comment by tom-james-watson** [comment]
I think the answer is to just not do that to be honest. Nobody has complained about this in the years this extension has been around so I think it's fine to just assume that people will login with www.reddit.com (and therefore old.reddit.com).
