### ISSUE TITLE
Sometimes old.reddit.com gives me the new experience

### ISSUE THREAD

**Issue by tom1952** [tom-james-watson/old-reddit-redirect#62]
Sometimes old.reddit.com still gives me the new experience.  If I change the URL to any two letter combo: like og.reddit.com then I successfully get the old experience.

Any idea why?  If not, is it possible to make the redirect location configurable so that I can have it go to "og.reddit.com" instead?

Firefox 96.0.1
Old Reddit Redirect 1.6.0

Screenshot:

![image](https://user-images.githubusercontent.com/58863785/150590476-b1acba83-a961-46e8-aa73-ce07879ee81d.png)

**Comment by tom-james-watson** [comment]
I've never seen this myself and haven't heard about anyone else seeing this, so going to close this out.
