### ISSUE TITLE
Does not work on Vivaldi

### ISSUE THREAD

**Issue by spoergsmaal** [tom-james-watson/old-reddit-redirect#64]
that's pretty much it :(

Vivaldi version: 5.1.2567.49 (Stable channel) (arm64)
OS: macOS Monterey 12.2
Device: Macbook Air (M1, 2020)

worked flawlessly on firefox, but i recently switched to vivaldi and now nothing happens when i click a reddit link. i just get the new, inferior "experience"

**Comment by tom-james-watson** [comment]
I only support Firefox and Chrome - can't make any promises about what happens on other browsers, I'm afraid.
