### ISSUE TITLE
Add an option to redirect to old.reddit.com only when browsing in private/incognito windows

### ISSUE THREAD

**Issue by navinthomas** [tom-james-watson/old-reddit-redirect#67]
I have opted out from the Reddit redesign via my Reddit account's preferences. So, I don't need to redirect to old.reddit.com to get the old reddit experience. The normal www.reddit.com url works for me. However, I would like my browser to redirect to old.reddit.com when I am browsing in private/incognito windows. Can this be implemented somehow?

**Comment by tom-james-watson** [comment]
I would recommend just using the extension, that's exactly what it would achieve. It would redirect www.reddit.com to old.reddit.com too, though.
