### ISSUE TITLE
Feature suggestion: toolbar menu toggle

### ISSUE THREAD

**Issue by joootdooot** [tom-james-watson/old-reddit-redirect#68]
Would you mind adding a simple toolbar menu toggle, when you have the free time to? It would increase usability as I access the new reddit sometimes to use the features. Thanks!

**Comment by tom-james-watson** [comment]
You can access new reddit at new.reddit.com. I would like to keep the app simple, so I don't want to add toolbar menus or anything like that. Thanks!

**Comment by DoctressWasTaken** [comment]
> You can access new reddit at new.reddit.com

fyi, this does not work anymore (Can't tell if it ever did work as I haven't been using the extension for too long), but opening a page under `new.reddit.com` will just redirect to reddit which then redirects to old.reddit via the extension.

![image](https://github.com/tom-james-watson/old-reddit-redirect/assets/60757347/ce4742ee-8fa3-4913-a8b2-c985e28d092a)

**Comment by tom-james-watson** [comment]
Yeh they got rid of the subdomain, it just redirects now. There is sh.reddit.com for new new reddit, which does work.

**Comment by tom-james-watson** [comment]
The last comment was incorrext - we just need to add  a specific rule for the manifest V3 version: https://github.com/tom-james-watson/old-reddit-redirect/issues/122

**Comment by tom-james-watson** [comment]
FYI as of version 3.0.0 you can now toggle the extension on and off by clicking its icon.
