### ISSUE TITLE
HTTPS request throws an error with HTTPS Everywhere

### ISSUE THREAD

**Issue by pumafish** [tom-james-watson/old-reddit-redirect#7]
I have both HTTPS Everywhere and Old Reddit Redirect extensions installed. It looks like HTTPS Everywhere takes control of the HTTPS redirect and both Firefox and Chrome will report it as an "extension error" because Old Reddit Redirect couldn't redirect to HTTPS itself. Normally a good error to see that it failed, however I know what's causing the issue. 

Is this something either extension could address/create an exception for? Or is this just a core function of how the browsers address 2 different extensions trying to do the same thing, and would require a major rework of Old Reddit Direct?

**Comment by tom-james-watson** [comment]
Hello, thanks for your bug report.

Chrome doesn't like having two extensions trying to make a redirect for the same page, which is understandable. You can add a rule to HTTPS Everywhere to not redirect reddit.com, which should stop that error from happening.
