### ISSUE TITLE
Add support for .onion domains

### ISSUE THREAD

**Issue by m3thm4th** [tom-james-watson/old-reddit-redirect#71]
Reddit launched official .onion domains

https://old.reddit.com/r/redditsecurity/comments/yd6hqg/reddit_onion_service_launch/

Add support for them to redirect to https://old.reddittorjg6rue252oqsxryoxengawnmo46qy4kyii5wtqnwfj4ooad.onion/

This would need some kind of switch to select either the clearnet or the Tor instance

**Comment by tom-james-watson** [comment]
Sorry but I think that's niche enough that it's not worth complicating the extension

**Comment by m3thm4th** [comment]
You have a userbase of more than 130k people, would you consider making a poll about it? Onion domains launch was done pretty much low-key, I myself found about it by chance, many users probably don't even know of their existence.

**Comment by tom-james-watson** [comment]
Yeah I hadn't seen it myself either till you posted it.

If lots of people come asking about it here then I can reconsider.
