### ISSUE TITLE
Clicking "load more comments" hangs with "loading..." showing

### ISSUE THREAD

**Issue by migueln1987** [tom-james-watson/old-reddit-redirect#74]
When clicking the "load more comments" link it doesn't load the comments. It keeps showing "loading..."

Firefox Browser Extended Support Release 102.7.0esr(64-bit)

Screenshot attached:
<img width="787" alt="Screenshot 2023-02-10 at 4 05 19 PM" src="https://user-images.githubusercontent.com/8152029/218207834-57137da7-ff61-4af9-89db-74d09228f780.png">

**Comment by tom-james-watson** [comment]
If that happens, it's not anything to do with this extension - it doesn't touch anything to do with that button or the loading of comments.
