### ISSUE TITLE
[Request] Support for chromium

### ISSUE THREAD

**Issue by MetalKnight56** [tom-james-watson/old-reddit-redirect#76]
Please add support for chromium, i beg you, i can't keep up with this new design, my whole family has abandoned me and i'm not lonely, starving, with cold and now this shit. I pay my taxes and i would really appreciatte if you could save us (chromium users)

**Comment by tom-james-watson** [comment]
You don't need to do anything special for chromium, just go to https://chrome.google.com/webstore/detail/old-reddit-redirect/dneaehbmnbhcippjikoajpoabadpodje and press install.
