### ISSUE TITLE
doesn't redirect sh.reddit.com to old.reddit.com

### ISSUE THREAD

**Issue by Mohab12345678** [tom-james-watson/old-reddit-redirect#77]

**Comment by tom-james-watson** [comment]
Seems to be a next-gen ui that will eventually become the default mobile ui - https://twitter.com/ricefield/status/1414714116493565956.

To be honest I think it's ok for it not to redirect, just like we don't redirect new.reddit.com for if you specifically want to use the new UI for something. I understand that the problem you're seeing is that people are linking to sh, but I think that's a pretty small edge case. Maybe if it becomes a big problem we can reconsider.
