### ISSUE TITLE
i.redd.it serves html

### ISSUE THREAD

**Issue by 9ary** [tom-james-watson/old-reddit-redirect#78]
It seems reddit recently started serving html instead of plain images on i.redd.it. The page is fairly simple, but it's quite annoying when you're trying to view a raw image.

Basic testing shows that they're using the Accept header to determine whether you're doing a direct page load or if it's in an `<img>` tag.
Removing the header seems to do the trick with curl. It seems the Firefox network inspector readds the header if you just remove it from "edit and resend", but removing the html and xml part, or even sending * or an empty value works.

**Comment by tom-james-watson** [comment]
Yeah I've noticed and been annoyed by this, too. 

Looks like in theory it should be possible with `onBeforeSendHeaders` (https://developer.chrome.com/docs/extensions/reference/webRequest/).

**Comment by 9ary** [comment]
Yep, I knew this was possible and I got it working. I'll prepare a PR.

**Comment by tom-james-watson** [comment]
I've actually just started looking at what is needed to migrate to manifest v3, which would require a completely different implementation. I'm not super sure everything is going to be possible in v3 for now, so yeh may as well put a PR together for now for v2.

**Comment by 9ary** [comment]
I assume this primarily affects Chrome? As far as I know, Firefox has no plans to change the webrequest API.

**Comment by tom-james-watson** [comment]
Yeah, I think it would only be needed for chrome. Will put it off for now. When it is actually finally deprecated for real we can address it.

**Comment by 9ary** [comment]
Looks like the exact same workaround applies here too, so adding the subdomain to the list should work. I'm not sure if it'd make sense to apply this to more/all subdomains of redd.it.

**Comment by tom-james-watson** [comment]
Interesting! Can you show an example of how you end up with one of those URLs? Eg a link to a post where the clicking on the image takes you to that link.

I'm just trying to work out how you end up on one of those pages.

**Comment by 9ary** [comment]
> `open image in new tab`

For what it's worth, you can middle click the image instead which will pretty much always go to i.redd.it.

**Comment by 9ary** [comment]
I haven't used macOS for a long time, but doesn't it support middle click with three fingers on the touchpad? Or are you using another input device? Worst case, there should also be a context menu option to "open link in new tab".

**Comment by pubct** [comment]
I don't speak code, but if I understood correctly that it's to remove the "border", then I think this might interest you too.

[Direct link to SFW comment with GIF](https://old.reddit.com/r/pcmasterrace/comments/15dvvee/wear_and_tear_on_my_mouse_after_a_few_weeks_of/ju4mzx4/)
