### ISSUE TITLE
NSFW v.redd.it not loading video

### ISSUE THREAD

**Issue by s1390** [tom-james-watson/old-reddit-redirect#8]
Hi,

v.redd.it links that are NSFW aren't loading the video. Non-NSFW video's are working. 

Example NSFW video: https://old.reddit.com/r/funny/comments/9jivgv/she_cut_me_off_so_i_had_a_surprise_for_her/

Example non-NSFW video: https://www.reddit.com/r/Unexpected/comments/9jly1e/attack/

This might be an issue with reddit, so feel free to close this issue if so. You may also think about excluding v.redd.it links that are NSFW for now.

Thanks.

**Comment by tom-james-watson** [comment]
Hmm - I can't reproduce this. https://old.reddit.com/r/funny/comments/9jivgv/she_cut_me_off_so_i_had_a_surprise_for_her/ loads fine for me.

Does it still happen for you?

**Comment by s1390** [comment]
Thanks for your reply!

Because it was working for you, I disabled all my extensions, and it's RES (probably some setting) that's doing this (only on old.reddit.com).
