### ISSUE TITLE
Repeat prompting for new permissions

### ISSUE THREAD

**Issue by Da3dalusCode** [tom-james-watson/old-reddit-redirect#82]
Both the firefox and chrome versions have been prompting for me to accept new permissions, repeatedly.  Almost every time I close and reopened the browsers. Seems like it started a week or two ago.

**Comment by tom-james-watson** [comment]
There have been two updates that required us to change the permissions that are being requested. This was to stop Reddit from turning direct image links into HTML pages. I don't envisage there being any more any time soon.
