### ISSUE TITLE
Support sh.reddit.com and new.reddit.com

### ISSUE THREAD

**Issue by Rusenche** [tom-james-watson/old-reddit-redirect#83]
Support `sh.reddit.com` and `new.reddit.com`.

https://old.reddit.com/r/uBlockOrigin/comments/151vlb5/

Please add to redirected domains and `sh.reddit.com` and `new.reddit.com`.

I know a similar thread exists: https://github.com/tom-james-watson/old-reddit-redirect/issues/77

**Comment by Rusenche** [comment]
You wrote that you want to see them that way. Please also respect others who do not want to see these sites in this way. Why don't you respect the other opinion?!

**Comment by tom-james-watson** [comment]
Because it's not possible to satisfy every user's desire. When there are people with the exact opposite desires, you have to choose one option that is not what one group wants. It has nothing to do with respect.

This is a free and open source project built and maintained in my free time, so please check your tone. There is of course nothing stopping you from forking the project and running your own extension.

**Comment by Rusenche** [comment]
You immediately approached ultra undemocratically. What is inappropriate in communication, you have applied it in full force!

If not every taste can be catered for - if there is an option in the extension one/many want to be able to choose any domain - then that would be another. Because, until recently, I also wondered why `new.reddit.com` always loads my non-classical design... (And now there is another domain inconvenient to use, `sh.reddit.com`). And there's practically nowhere to bookmark to choose exactly new.reddit.com to also have a classic design.

As an example - the Ublock origin extension - you choose which filters to use or not to use.

**Comment by tom-james-watson** [comment]
I open sourced this and welcome discussion and patches. To accuse me of a lack of respect is insulting and shows an entitlement that is unfortunately very common in open source projects.

You should reconsider what open source maintainers owe you and change your approach.

You have a level of entitlement and lack of respect that wo
