### ISSUE TITLE
When trying to open a picture get redirected to same page in r/funny

### ISSUE THREAD

**Issue by Nesproc** [tom-james-watson/old-reddit-redirect#88]
When trying to click on an image while the add-on is active, get redirected to the same post in r/funny no matter the image:

https://old.reddit.com/r/funny/comments/media/nice_hat/?url=https%3A%2F%2Fpreview.redd.it%2Fh3lf1ndcjajb1.jpg%3Fwidth%3D1324%26format%3Dpjpg%26auto%3Dwebp%26s%3Da4c8d76a6667ad36c396dddf63d8efb4d08d6c26

disabling the add-on resolves the issue

**Comment by Nesproc** [comment]
saw this was known an supposed to be fixed two weeks ago... missed the part where it is unfixable rn... closing

**Comment by tom-james-watson** [comment]
It's not unfixable - what you described should be fixed. Please make sure you've updated to the latest version of the extension.

**Comment by Nesproc** [comment]
ty - confirmed ... not sure why didn't auto-update but removed and re-added the extension working now and ty for the addon =)
