### ISSUE TITLE
new.reddit.com is redirecting to old.reddit.com

### ISSUE THREAD

**Issue by johnywith1n** [tom-james-watson/old-reddit-redirect#89]
`new.reddit.com` is supposed to be excluded from redirects but is redirecting to `old.reddit.com`,

I am on Firefox 116.0.3 and extension version 1.7.3

**Comment by tom-james-watson** [comment]
That shouldn't happen and I can't recreate it.

Check you have no other extensions performing redirects. Try disabling them one by one. Or disable Old Reddit Redirect and then see if it still happens.

**Comment by johnywith1n** [comment]
Disabled all other extensions and it still happens.

Disabled Old Reddit Redirect and it no longer happens

**Comment by tom-james-watson** [comment]
Can you please paste the URL that is being directed and the URL it is directed to?

Can you also please confirm what version of the extension you currently have?

**Comment by SiteRelEnby** [comment]
Same issue here. Might be some kind of addon conflict, I'll try to diagnose it later today or tomorrow when I have more time.

**Comment by SiteRelEnby** [comment]
Scratch the "later", seems it's a conflict with Privacy Badger.

**Comment by Lethalmathematix** [comment]
Can reproduce on FF, Chrome, and Edge. Lates versions of browser and extension.

Only other extension I have running is uBlock Origin.

**Comment by tom-james-watson** [comment]
It looks like Reddit has decided to start redirecting https://new.reddit.com/ to https://www.reddit.com/. Once Old Reddit Redirect sees https://www.reddit.com, it understandably redirects it to https://old.reddit.com.

The problem is with Reddit - I don't know why they are doing that redirect. It also seems to be inconsistent, it seems to depend on the browser session. I don't think there's anything we can do about this - if Reddit wants to deprecate https://new.reddit.com then there's not a whole lot we can do.

**Comment by thismoon** [comment]
@tom-james-watson the extension "[Foxy Gestures](https://addons.mozilla.org/en-US/firefox/addon/foxy-gestures/)" has a feature where you can click on the extension icon to temporarily disable it for the current tab (also the icon color changes)

Maybe you can implement a similar feature where you click on the extension icon and it gets disabled on the current tab/temporarily on all tabs

**For users**:  I found a work around! replace `old` with `sh` and it will show the new reddit
e.g. `sh.reddit.com`.

**Comment by SiteRelEnby** [comment]
> **For users**: I found a work around! replace `old` with `sh` and it will show the new reddit e.g. `sh.reddit.com`.

Wow, TIL. That's even worse than new.reddit.com. Is the rest of the subdomain abbreviation `itty`?

**Comment by tom-james-watson** [comment]
Haha. What I actually meant was that it would replace new reddit mobile, I don't think it will replace desktop.
