### ISSUE TITLE
Fix for https://www.reddit.com/poll

### ISSUE THREAD

**Issue by zamicol** [tom-james-watson/old-reddit-redirect#9]
https://old.reddit.com/poll/* doesn't exist.  https://www.reddit.com/poll/* needs to be excluded.

**Comment by tom-james-watson** [comment]
Hello - thanks for your PR.

I've not come across polls before. Have you got an example link to one? Thanks!

**Comment by zamicol** [comment]
Here's a link to a discussion thread: https://www.reddit.com/r/ethtrader/comments/9ymlw4/whose_the_biggest_bagholder_of_them_all

And the poll itself:
https://www.reddit.com/poll/9ymlw4

**Comment by tom-james-watson** [comment]
All looks good - have merged and will release a new version. Thanks again.
