### ISSUE TITLE
Opening images or clicking on an image link takes me to a post from 11 years ago

### ISSUE THREAD

**Issue by DxAxxxTyriel** [tom-james-watson/old-reddit-redirect#92]
Sorry, accidentally pressed enter. Here's the full info:

Lets suppose I go to https://old.reddit.com/r/all/. I see a post that is from /r/memes. The link to the comments of the post is https://old.reddit.com/r/memes/comments/16639dl/why_does_it_always_have_to_be_this_way/. However, there is an image and it has a link. The link being: https://i.redd.it/192mi6ov4elb1.jpg

If I copy paste this link into a new tab and go to it, takes me to: https://old.reddit.com/r/funny/comments/media/nice_hat/?url=https%3A%2F%2Fi.redd.it%2F192mi6ov4elb1.jpg

If I copy paste the URL into a new tab, it happens. If I click on the post title, it happens. If i click on the image thumbnail, it happens. It constantly whenever the URL is https://i.redd.it/, it will 100% happen. Any idea why? I'm pretty sure it is due to the extension, but I could be wrong.

I have the following extensions: BetterTTV, Disable YouTube Cards, FrankerFaceZ, Old Reddit Redirect, uBlock Origin, Youtube-shorts block.

Any ideas?

**Comment by DxAxxxTyriel** [comment]
Checked the closed subjects and found out I needed to update the extension.

Thanks and sorry.

**Comment by tom-james-watson** [comment]
No problem 👍
