### ISSUE TITLE
Support new-style comment links

### ISSUE THREAD

**Issue by masasin** [tom-james-watson/old-reddit-redirect#97]
Over the last week or two, reddit has changed the way comment permalinks are made on the new interface.

The old way: https://reddit.com/r/subreddit_name/comments/thread_id/thread_title/comment_id/

The new way: https://reddit.com/r/subreddit_name/s/combined_id

The problem with the new way is that the /s/ part gets interpreted as submit in old reddit, so the comment does not get resolved, and you're redirected to the submission page.

One suggestion is to filter out that particular structure, allow it to go to new reddit, where the URL is resolved to the old-style permalink. Then the extension can trigger again by changing it back to the old reddit.

**Comment by tom-james-watson** [comment]
Links like https://www.reddit.com/r/comics/s/TjDGhcl22d will now be handled as of version 1.8.0.

Thanks for the report and for the suggestion of how to handle it - that works well 👍

**Comment by tom-james-watson** [comment]
Submitted to Firefox and Chrome extension stores.
