### ISSUE TITLE
opening links doesn't work - redirects to "submit link".

### ISSUE THREAD

**Issue by martinboson** [tom-james-watson/old-reddit-redirect#98]
If I try to click on any link, for example the one in this comment: https://old.reddit.com/r/thalassophobia/comments/17afpa5/deadheads_are_water_soaked_logs_that_float/k5cvsdz/
, it sends me to a submit link page: https://old.reddit.com/r/AskReddit/submit?url=https%3A%2F%2FemeaNRDHYJ%3Futm_source%3Dreddit%26utm_medium%3Dusertext%26utm_name%3Dthalassophobia%26utm_content%3Dt1_k5cvsdz

I'm on firefox,  117.0.1 (64-bit), win 10.

**Comment by tom-james-watson** [comment]
Can you expand a bit on how to reproduce this? I'm not seeing any issues, but I'm not sure what you mean by "any link"?

**Comment by martinboson** [comment]
any link to a comment on reddit, I should clarify.

**Comment by martinboson** [comment]
If I copy the link and paste it, it turns out like this: https://old.reddit.com/r/AskReddit/submit?url=https%3A%2F%2FemeaNRDHYJ

**Comment by tom-james-watson** [comment]
Oh, I see you mean the link actually in the linked comment, which is to https://www.reddit.com/r/AskReddit/s/emeaNRDHYJ. This was fixed in https://github.com/tom-james-watson/old-reddit-redirect/issues/97. Just need to wait a few days for the update to get pushed out to users.
