### ISSUE TITLE
opening a picture from a gallery redirect to a pic of lady gaga called "nice hat"

### ISSUE THREAD

**Issue by martinboson** [tom-james-watson/old-reddit-redirect#99]
This might be similar to #95 and #98, I haven't read all the closed issues...

So if click on any of the pics in this gallery: https://old.reddit.com/r/pics/comments/17jw61e/this_is_my_beautiful_commute_to_work/

it sends me to this link of lady gaga: https://old.reddit.com/r/funny/comments/media/nice_hat/?url=https%3A%2F%2Fpreview.redd.it%2Fvfcjkg730dxb1.jpg%3Fwidth%3D3024%26format%3Dpjpg%26auto%3Dwebp%26s%3D3bb001f0366f02ac77cd0485a73aa057494df8fa

**Comment by tom-james-watson** [comment]
This is https://github.com/tom-james-watson/old-reddit-redirect/issues/97, which is already fixed. You just need to update the extension. Some people seem to need to manually remove and re-add the extension to get the update, so maybe try that if it's not updating. I think it's a bug with Firefox.
